/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dingsigang_ndktest_NDKTestUtil */

#ifndef _Included_com_example_dingsigang_ndktest_NDKTestUtil
#define _Included_com_example_dingsigang_ndktest_NDKTestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dingsigang_ndktest_NDKTestUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_com_example_dingsigang_ndktest_NDKTestUtil_test
//        (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_soubu_goldensteward_utils_BitmapUtils_compressImage(JNIEnv *,
                                                                               jobject ,
                                                                               jobject ,
                                                                               int ,
                                                                               int , int ,
                                                                               jbyteArray ,
                                                                               jboolean ) {

#ifdef __cplusplus
}
#endif
#endif
